#!/usr/bin/env python3
"""Run testbenches with PEX-extracted parasitic netlists.

This replaces the ideal schematic subcircuits with parasitic-extracted
versions from Magic, enabling post-layout simulation.

Usage:
    python -m project.layout.verify.pex_sim --component strongarm --corner tt --temp 27
    python -m project.layout.verify.pex_sim --component all --corner tt,ss,ff --temp 27

Requires PEX netlists in output/layout/<component>/<component>_pex.spice
(generated by: python -m project.layout.verify.run --step pex)
"""
import argparse
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
PEX_DIR = ROOT / "output" / "layout"

# Map component → testbench module
TB_MAP = {
    "strongarm": "project.testbenches.tb_strongarm",
    "charge_dac": "project.testbenches.tb_charge_dac",
    "sample_hold_bank": "project.testbenches.tb_sample_hold_bank",
    "imc_crossbar": "project.testbenches.tb_imc_crossbar",
    "interleaved_adc": "project.testbenches.tb_interleaved_adc",
    "async_ctrl": "project.testbenches.tb_async_ctrl",
}


def get_pex_netlist(name: str) -> Path:
    """Get path to PEX netlist for a component."""
    pex_path = PEX_DIR / name / f"{name}_pex.spice"
    if not pex_path.exists():
        raise FileNotFoundError(
            f"PEX netlist not found: {pex_path}\n"
            f"Run first: python -m project.layout.verify.run -c {name} -s pex"
        )
    return pex_path


def make_pex_generator(name: str):
    """Create a generate() function that returns PEX SPICE instead of ideal."""
    pex_path = get_pex_netlist(name)
    pex_text = pex_path.read_text()

    def generate() -> str:
        return pex_text

    return generate


def run_pex_testbench(name: str, corners: list[str], temps: list[int]):
    """Run a component's testbench with PEX netlist."""
    import importlib

    pex_path = get_pex_netlist(name)
    print(f"[PEX-SIM] {name}: using {pex_path}")

    # Import the testbench
    tb_mod = importlib.import_module(TB_MAP[name])

    # Override the generate function to use PEX netlist
    pex_generate = make_pex_generator(name)

    # The testbench should have a run() function that accepts generate
    if hasattr(tb_mod, "run"):
        for corner in corners:
            for temp in temps:
                print(f"\n[PEX-SIM] {name} @ {corner}/{temp}°C")
                try:
                    sys.argv = [
                        "pex_sim",
                        f"--corner={corner}",
                        f"--temp={temp}",
                    ]
                    tb_mod.run(pex_generate, name)
                except Exception as e:
                    print(f"[PEX-SIM] {name} @ {corner}/{temp}°C: FAIL — {e}")
    else:
        print(f"[PEX-SIM] {name}: testbench has no run() function, skipping")


def main():
    parser = argparse.ArgumentParser(description="Post-layout PEX simulation")
    parser.add_argument(
        "--component", "-c",
        choices=list(TB_MAP.keys()) + ["all"],
        default="all",
    )
    parser.add_argument("--corner", default="tt", help="Corners: tt,ss,ff")
    parser.add_argument("--temp", default="27", help="Temperatures: -40,27,125")
    args = parser.parse_args()

    corners = args.corner.split(",")
    temps = [int(t) for t in args.temp.split(",")]

    components = list(TB_MAP.keys()) if args.component == "all" else [args.component]

    for name in components:
        try:
            run_pex_testbench(name, corners, temps)
        except FileNotFoundError as e:
            print(f"[SKIP] {name}: {e}")
        except Exception as e:
            print(f"[ERR] {name}: {e}")


if __name__ == "__main__":
    sys.path.insert(0, str(ROOT))
    main()
